#!/bin/bash

echo "Mounting drives..."

if [[ $(cat /etc/samba/smb.conf | grep "/etc/samba/drives.conf") == "" ]]; then
    echo "Adding include to the SAMBA configuration..."
    sudo sh -c "echo \"include = /etc/samba/drives.conf\" > /etc/samba/smb.conf"
fi

sudo fdisk -l | grep "/dev/sd" | grep -v "Disk " | grep "FAT" | awk '{print $1}' | while read -r dev; do
    sudo udisks mount -b $dev -o ro --no-user-interaction
done

sudo sh -c "echo \"\" > /etc/samba/drives.conf"

sudo ls /media | while read -r mount; do
    echo "Creating SAMBA share '$mount'..."

    sudo sh -c "echo \"[$mount]\" >> /etc/samba/drives.conf"
    sudo sh -c "echo \"comment = Drive\" >> /etc/samba/drives.conf"
    sudo sh -c "echo \"browseable = yes\" >> /etc/samba/drives.conf"
    sudo sh -c "echo \"path = /media/$mount\" >> /etc/samba/drives.conf"
    sudo sh -c "echo \"guest ok = no\" >> /etc/samba/drives.conf"
    sudo sh -c "echo \"read only = yes\" >> /etc/samba/drives.conf"
    sudo sh -c "echo \"create mask = 0700\" >> /etc/samba/drives.conf"
    sudo sh -c "echo \"\" >> /etc/samba/drives.conf"

done

sudo /etc/init.d/samba reload

echo "Done"
